#!/usr/bin/env python
import rospy
import numpy as np
from ros_helper.transform import TfApi

def time():
    t = rospy.Time.now()
    return t, t.to_sec()

if __name__ == '__main__':
    rospy.init_node('rviz_spray_sim_example_node')
    tfapi = TfApi(rospy)
    rate = rospy.Rate(100)
    trans = [0]*3
    _, t0 = time()

    while not rospy.is_shutdown():
        rtime, sec  = time()
        trans[1] = 0.5 * np.sin(sec - t0)
        tfapi.set_tf(rtime, trans, (0, 0, 0, 1), 'spray_frame', 'world')
        rate.sleep()
