#!/usr/bin/env python
import rospy
import pygame
import ros_helper.msgs_api.sensor as sens

"""
TODO: Update to use simple_pub_sub
"""

TOPICS = ['keyboard/binary', 'keyboard/keyup', 'keyboard/keydown']

class KeyboardPublisher(object):

    def __init__(self):
        self.msg_binary = sens.KeyboardMsg()
        self.pub = {}
        for t in TOPICS: self.pub[t] = rospy.Publisher(t, sens.Keyboard, queue_size=1)

    def update(self, event):

        # Init
        self.msg_binary.add_time(rospy.Time.now())
        msg_keyup = sens.KeyboardMsg(rospy.Time.now())
        msg_keydown = sense.KeyboardMsg(rospy.Time.now())

        # Transfer keyboard state in pygame -> msgs
        for ev in pygame.event.get():
            if ev.type == pygame.KEYUP:
                self.msg_binary[ev.key] = 0
                msg_keyup[ev.key] = 1
            if ev.type == pygame.KEYDOWN:
                self.msg_binary[ev.key] = 1
                msg_keydown[ev.key] = 1

        # Publish msgs
        for t, m in zip(TOPICS,[self.msg_binary, msg_keyup, msg_keydown]): self.pub[t].publish(m)

if __name__=='__main__':
    pygame.init()
    pygame.display.set_mode((1, 1))
    pygame.display.set_caption('keyboard')
    rospy.init_node('keyboad_node')
    if rospy.has_param('~hz'):
        hz = rospy.get_param('~hz')
    else:
        hz = 100.0
    rospy.Timer(rospy.Duration(1.0/hz), KeyboardPublisher().update)
    rospy.spin()
