#!/usr/bin/env python
import rospy
import pygame
from ros_helper.msgs.sensor import KeyboardMsg
from ros_helper.simple_pub_sub import SimplePublisher

"""
TODO: Update to use simple_pub_sub
"""

msg = KeyboardMsg()

def generate_message():
    msg.time = rospy.Time.now()

    for ev in pygame.event.get():
        if ev.type==pygame.KEYUP:
            msg[ev.key] = 0
        if ev.type==pygame.KEYDOWN:
            msg[ev.key] = 1

    return msg

if __name__=='__main__':
    pygame.init()
    pygame.display.set_mode((1, 1))
    pygame.display.set_caption('keyboard')
    rospy.init_node('keyboad_node')
    if rospy.has_param('~hz'):
        hz = rospy.get_param('~hz')
    else:
        hz = 100.0
    SimplePublisher(rospy, 'keyboard', KeyboardMsg, hz, gen_msg_handle=generate_message)
    rospy.spin()
