#!/usr/bin/env python
import rospy
import message_filters as mf
import ros_helper.msgs_api.sensor as sens

class MultiJoyParser(object):

    def __init__(self):
        self.pub = rospy.Publisher('multijoy', sens.MultiJoy, queue_size=1)
        joytopics = rospy.get_param('~joytopics') # e.g. in launch file use <rosparam param="joytopics">[joy1, joy2, joy3, joy4]</rosparam>
        mf.ApproximateTimeSynchronizer([mf.Subscriber(t, sens.Joy) for t in joytopics], 10, len(joytopics)*100).registerCallback(self.callback)

    def callback(self, *joys):
        self.pub.publish(sens.MultiJoyMsg(rospy.Time.now(), joys))

if __name__=='__main__':
    rospy.init_node('multijoy_node')
    MultiJoyParser()
    rospy.spin()
    
