#!/usr/bin/env python
import rospy
import ros_helper.msgs_api.visualization as vis
from ros_helper.simple_pub_sub import SimplePublisher

class MeshPublisher(SimplePublisher):

    def __init__(self):
        self.filename = rospy.get_param('~filename')
        self.frame_id = rospy.get_param('~frame_id')
        self.scale = rospy.get_param('~scale')
        self.color = rospy.get_param('~color')
        super(MeshPublisher, self).__init__(rospy, rospy.get_param('~topic_name'), vis.Marker) 

    def generate_message(self):
        return vis.StlMeshMsg(self.filename, rospy.Time.now(), self.frame_id, self.scale, self.color)

if __name__=='__main__':
    rospy.init_node('mesh_publisher_node')
    rospy.Timer(rospy.Duration(1.0/50.0), MeshPublisher().update)
    rospy.spin()
    
                
