# generated using gen.py, DO NOT USE!

raise ImportError("DO NOT USE, this file was generated by gen.py")

class GoalIDMsg(GoalID):

    def __init__(self):
        super(GoalIDMsg, self).__init__()
        raise NotImplementedError("GoalIDMsg is not yet implemented")

class GoalStatusMsg(GoalStatus):

    def __init__(self):
        super(GoalStatusMsg, self).__init__()
        raise NotImplementedError("GoalStatusMsg is not yet implemented")

class GoalStatusArrayMsg(GoalStatusArray):

    def __init__(self):
        super(GoalStatusArrayMsg, self).__init__()
        raise NotImplementedError("GoalStatusArrayMsg is not yet implemented")

