# generated using gen.py, DO NOT USE!

raise ImportError("DO NOT USE, this file was generated by gen.py")

class GetMapActionMsg(GetMapAction):

    def __init__(self):
        super(GetMapActionMsg, self).__init__()
        raise NotImplementedError("GetMapActionMsg is not yet implemented")

class GetMapActionFeedbackMsg(GetMapActionFeedback):

    def __init__(self):
        super(GetMapActionFeedbackMsg, self).__init__()
        raise NotImplementedError("GetMapActionFeedbackMsg is not yet implemented")

class GetMapActionGoalMsg(GetMapActionGoal):

    def __init__(self):
        super(GetMapActionGoalMsg, self).__init__()
        raise NotImplementedError("GetMapActionGoalMsg is not yet implemented")

class GetMapActionResultMsg(GetMapActionResult):

    def __init__(self):
        super(GetMapActionResultMsg, self).__init__()
        raise NotImplementedError("GetMapActionResultMsg is not yet implemented")

class GetMapFeedbackMsg(GetMapFeedback):

    def __init__(self):
        super(GetMapFeedbackMsg, self).__init__()
        raise NotImplementedError("GetMapFeedbackMsg is not yet implemented")

class GetMapGoalMsg(GetMapGoal):

    def __init__(self):
        super(GetMapGoalMsg, self).__init__()
        raise NotImplementedError("GetMapGoalMsg is not yet implemented")

class GetMapResultMsg(GetMapResult):

    def __init__(self):
        super(GetMapResultMsg, self).__init__()
        raise NotImplementedError("GetMapResultMsg is not yet implemented")

class GridCellsMsg(GridCells):

    def __init__(self):
        super(GridCellsMsg, self).__init__()
        raise NotImplementedError("GridCellsMsg is not yet implemented")

class MapMetaDataMsg(MapMetaData):

    def __init__(self):
        super(MapMetaDataMsg, self).__init__()
        raise NotImplementedError("MapMetaDataMsg is not yet implemented")

class OccupancyGridMsg(OccupancyGrid):

    def __init__(self):
        super(OccupancyGridMsg, self).__init__()
        raise NotImplementedError("OccupancyGridMsg is not yet implemented")

class OdometryMsg(Odometry):

    def __init__(self):
        super(OdometryMsg, self).__init__()
        raise NotImplementedError("OdometryMsg is not yet implemented")

class PathMsg(Path):

    def __init__(self):
        super(PathMsg, self).__init__()
        raise NotImplementedError("PathMsg is not yet implemented")

