# generated using gen.py, DO NOT USE!

raise ImportError("DO NOT USE, this file was generated by gen.py")

class BatteryStateMsg(BatteryState):

    def __init__(self):
        super(BatteryStateMsg, self).__init__()
        raise NotImplementedError("BatteryStateMsg is not yet implemented")

class CameraInfoMsg(CameraInfo):

    def __init__(self):
        super(CameraInfoMsg, self).__init__()
        raise NotImplementedError("CameraInfoMsg is not yet implemented")

class ChannelFloat32Msg(ChannelFloat32):

    def __init__(self):
        super(ChannelFloat32Msg, self).__init__()
        raise NotImplementedError("ChannelFloat32Msg is not yet implemented")

class CompressedImageMsg(CompressedImage):

    def __init__(self):
        super(CompressedImageMsg, self).__init__()
        raise NotImplementedError("CompressedImageMsg is not yet implemented")

class FluidPressureMsg(FluidPressure):

    def __init__(self):
        super(FluidPressureMsg, self).__init__()
        raise NotImplementedError("FluidPressureMsg is not yet implemented")

class IlluminanceMsg(Illuminance):

    def __init__(self):
        super(IlluminanceMsg, self).__init__()
        raise NotImplementedError("IlluminanceMsg is not yet implemented")

class ImageMsg(Image):

    def __init__(self):
        super(ImageMsg, self).__init__()
        raise NotImplementedError("ImageMsg is not yet implemented")

class ImuMsg(Imu):

    def __init__(self):
        super(ImuMsg, self).__init__()
        raise NotImplementedError("ImuMsg is not yet implemented")

class JointStateMsg(JointState):

    def __init__(self):
        super(JointStateMsg, self).__init__()
        raise NotImplementedError("JointStateMsg is not yet implemented")

class JoyMsg(Joy):

    def __init__(self):
        super(JoyMsg, self).__init__()
        raise NotImplementedError("JoyMsg is not yet implemented")

class JoyFeedbackMsg(JoyFeedback):

    def __init__(self):
        super(JoyFeedbackMsg, self).__init__()
        raise NotImplementedError("JoyFeedbackMsg is not yet implemented")

class JoyFeedbackArrayMsg(JoyFeedbackArray):

    def __init__(self):
        super(JoyFeedbackArrayMsg, self).__init__()
        raise NotImplementedError("JoyFeedbackArrayMsg is not yet implemented")

class LaserEchoMsg(LaserEcho):

    def __init__(self):
        super(LaserEchoMsg, self).__init__()
        raise NotImplementedError("LaserEchoMsg is not yet implemented")

class LaserScanMsg(LaserScan):

    def __init__(self):
        super(LaserScanMsg, self).__init__()
        raise NotImplementedError("LaserScanMsg is not yet implemented")

class MagneticFieldMsg(MagneticField):

    def __init__(self):
        super(MagneticFieldMsg, self).__init__()
        raise NotImplementedError("MagneticFieldMsg is not yet implemented")

class MultiDOFJointStateMsg(MultiDOFJointState):

    def __init__(self):
        super(MultiDOFJointStateMsg, self).__init__()
        raise NotImplementedError("MultiDOFJointStateMsg is not yet implemented")

class MultiEchoLaserScanMsg(MultiEchoLaserScan):

    def __init__(self):
        super(MultiEchoLaserScanMsg, self).__init__()
        raise NotImplementedError("MultiEchoLaserScanMsg is not yet implemented")

class NavSatFixMsg(NavSatFix):

    def __init__(self):
        super(NavSatFixMsg, self).__init__()
        raise NotImplementedError("NavSatFixMsg is not yet implemented")

class NavSatStatusMsg(NavSatStatus):

    def __init__(self):
        super(NavSatStatusMsg, self).__init__()
        raise NotImplementedError("NavSatStatusMsg is not yet implemented")

class PointCloudMsg(PointCloud):

    def __init__(self):
        super(PointCloudMsg, self).__init__()
        raise NotImplementedError("PointCloudMsg is not yet implemented")

class PointCloud2Msg(PointCloud2):

    def __init__(self):
        super(PointCloud2Msg, self).__init__()
        raise NotImplementedError("PointCloud2Msg is not yet implemented")

class PointFieldMsg(PointField):

    def __init__(self):
        super(PointFieldMsg, self).__init__()
        raise NotImplementedError("PointFieldMsg is not yet implemented")

class RangeMsg(Range):

    def __init__(self):
        super(RangeMsg, self).__init__()
        raise NotImplementedError("RangeMsg is not yet implemented")

class RegionOfInterestMsg(RegionOfInterest):

    def __init__(self):
        super(RegionOfInterestMsg, self).__init__()
        raise NotImplementedError("RegionOfInterestMsg is not yet implemented")

class RelativeHumidityMsg(RelativeHumidity):

    def __init__(self):
        super(RelativeHumidityMsg, self).__init__()
        raise NotImplementedError("RelativeHumidityMsg is not yet implemented")

class TemperatureMsg(Temperature):

    def __init__(self):
        super(TemperatureMsg, self).__init__()
        raise NotImplementedError("TemperatureMsg is not yet implemented")

class TimeReferenceMsg(TimeReference):

    def __init__(self):
        super(TimeReferenceMsg, self).__init__()
        raise NotImplementedError("TimeReferenceMsg is not yet implemented")

