# generated using gen.py, DO NOT USE!

raise ImportError("DO NOT USE, this file was generated by gen.py")

class BoolMsg(Bool):

    def __init__(self):
        super(BoolMsg, self).__init__()
        raise NotImplementedError("BoolMsg is not yet implemented")

class ByteMsg(Byte):

    def __init__(self):
        super(ByteMsg, self).__init__()
        raise NotImplementedError("ByteMsg is not yet implemented")

class ByteMultiArrayMsg(ByteMultiArray):

    def __init__(self):
        super(ByteMultiArrayMsg, self).__init__()
        raise NotImplementedError("ByteMultiArrayMsg is not yet implemented")

class CharMsg(Char):

    def __init__(self):
        super(CharMsg, self).__init__()
        raise NotImplementedError("CharMsg is not yet implemented")

class ColorRGBAMsg(ColorRGBA):

    def __init__(self):
        super(ColorRGBAMsg, self).__init__()
        raise NotImplementedError("ColorRGBAMsg is not yet implemented")

class DurationMsg(Duration):

    def __init__(self):
        super(DurationMsg, self).__init__()
        raise NotImplementedError("DurationMsg is not yet implemented")

class EmptyMsg(Empty):

    def __init__(self):
        super(EmptyMsg, self).__init__()
        raise NotImplementedError("EmptyMsg is not yet implemented")

class Float32Msg(Float32):

    def __init__(self):
        super(Float32Msg, self).__init__()
        raise NotImplementedError("Float32Msg is not yet implemented")

class Float32MultiArrayMsg(Float32MultiArray):

    def __init__(self):
        super(Float32MultiArrayMsg, self).__init__()
        raise NotImplementedError("Float32MultiArrayMsg is not yet implemented")

class Float64Msg(Float64):

    def __init__(self):
        super(Float64Msg, self).__init__()
        raise NotImplementedError("Float64Msg is not yet implemented")

class Float64MultiArrayMsg(Float64MultiArray):

    def __init__(self):
        super(Float64MultiArrayMsg, self).__init__()
        raise NotImplementedError("Float64MultiArrayMsg is not yet implemented")

class HeaderMsg(Header):

    def __init__(self):
        super(HeaderMsg, self).__init__()
        raise NotImplementedError("HeaderMsg is not yet implemented")

class Int16Msg(Int16):

    def __init__(self):
        super(Int16Msg, self).__init__()
        raise NotImplementedError("Int16Msg is not yet implemented")

class Int16MultiArrayMsg(Int16MultiArray):

    def __init__(self):
        super(Int16MultiArrayMsg, self).__init__()
        raise NotImplementedError("Int16MultiArrayMsg is not yet implemented")

class Int32Msg(Int32):

    def __init__(self):
        super(Int32Msg, self).__init__()
        raise NotImplementedError("Int32Msg is not yet implemented")

class Int32MultiArrayMsg(Int32MultiArray):

    def __init__(self):
        super(Int32MultiArrayMsg, self).__init__()
        raise NotImplementedError("Int32MultiArrayMsg is not yet implemented")

class Int64Msg(Int64):

    def __init__(self):
        super(Int64Msg, self).__init__()
        raise NotImplementedError("Int64Msg is not yet implemented")

class Int64MultiArrayMsg(Int64MultiArray):

    def __init__(self):
        super(Int64MultiArrayMsg, self).__init__()
        raise NotImplementedError("Int64MultiArrayMsg is not yet implemented")

class Int8Msg(Int8):

    def __init__(self):
        super(Int8Msg, self).__init__()
        raise NotImplementedError("Int8Msg is not yet implemented")

class Int8MultiArrayMsg(Int8MultiArray):

    def __init__(self):
        super(Int8MultiArrayMsg, self).__init__()
        raise NotImplementedError("Int8MultiArrayMsg is not yet implemented")

class MultiArrayDimensionMsg(MultiArrayDimension):

    def __init__(self):
        super(MultiArrayDimensionMsg, self).__init__()
        raise NotImplementedError("MultiArrayDimensionMsg is not yet implemented")

class MultiArrayLayoutMsg(MultiArrayLayout):

    def __init__(self):
        super(MultiArrayLayoutMsg, self).__init__()
        raise NotImplementedError("MultiArrayLayoutMsg is not yet implemented")

class StringMsg(String):

    def __init__(self):
        super(StringMsg, self).__init__()
        raise NotImplementedError("StringMsg is not yet implemented")

class TimeMsg(Time):

    def __init__(self):
        super(TimeMsg, self).__init__()
        raise NotImplementedError("TimeMsg is not yet implemented")

class UInt16Msg(UInt16):

    def __init__(self):
        super(UInt16Msg, self).__init__()
        raise NotImplementedError("UInt16Msg is not yet implemented")

class UInt16MultiArrayMsg(UInt16MultiArray):

    def __init__(self):
        super(UInt16MultiArrayMsg, self).__init__()
        raise NotImplementedError("UInt16MultiArrayMsg is not yet implemented")

class UInt32Msg(UInt32):

    def __init__(self):
        super(UInt32Msg, self).__init__()
        raise NotImplementedError("UInt32Msg is not yet implemented")

class UInt32MultiArrayMsg(UInt32MultiArray):

    def __init__(self):
        super(UInt32MultiArrayMsg, self).__init__()
        raise NotImplementedError("UInt32MultiArrayMsg is not yet implemented")

class UInt64Msg(UInt64):

    def __init__(self):
        super(UInt64Msg, self).__init__()
        raise NotImplementedError("UInt64Msg is not yet implemented")

class UInt64MultiArrayMsg(UInt64MultiArray):

    def __init__(self):
        super(UInt64MultiArrayMsg, self).__init__()
        raise NotImplementedError("UInt64MultiArrayMsg is not yet implemented")

class UInt8Msg(UInt8):

    def __init__(self):
        super(UInt8Msg, self).__init__()
        raise NotImplementedError("UInt8Msg is not yet implemented")

class UInt8MultiArrayMsg(UInt8MultiArray):

    def __init__(self):
        super(UInt8MultiArrayMsg, self).__init__()
        raise NotImplementedError("UInt8MultiArrayMsg is not yet implemented")

