# generated using gen.py, DO NOT USE!

raise ImportError("DO NOT USE, this file was generated by gen.py")

class ImageMarkerMsg(ImageMarker):

    def __init__(self):
        super(ImageMarkerMsg, self).__init__()
        raise NotImplementedError("ImageMarkerMsg is not yet implemented")

class InteractiveMarkerMsg(InteractiveMarker):

    def __init__(self):
        super(InteractiveMarkerMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerMsg is not yet implemented")

class InteractiveMarkerControlMsg(InteractiveMarkerControl):

    def __init__(self):
        super(InteractiveMarkerControlMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerControlMsg is not yet implemented")

class InteractiveMarkerFeedbackMsg(InteractiveMarkerFeedback):

    def __init__(self):
        super(InteractiveMarkerFeedbackMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerFeedbackMsg is not yet implemented")

class InteractiveMarkerInitMsg(InteractiveMarkerInit):

    def __init__(self):
        super(InteractiveMarkerInitMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerInitMsg is not yet implemented")

class InteractiveMarkerPoseMsg(InteractiveMarkerPose):

    def __init__(self):
        super(InteractiveMarkerPoseMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerPoseMsg is not yet implemented")

class InteractiveMarkerUpdateMsg(InteractiveMarkerUpdate):

    def __init__(self):
        super(InteractiveMarkerUpdateMsg, self).__init__()
        raise NotImplementedError("InteractiveMarkerUpdateMsg is not yet implemented")

class MarkerMsg(Marker):

    def __init__(self):
        super(MarkerMsg, self).__init__()
        raise NotImplementedError("MarkerMsg is not yet implemented")

class MarkerArrayMsg(MarkerArray):

    def __init__(self):
        super(MarkerArrayMsg, self).__init__()
        raise NotImplementedError("MarkerArrayMsg is not yet implemented")

class MenuEntryMsg(MenuEntry):

    def __init__(self):
        super(MenuEntryMsg, self).__init__()
        raise NotImplementedError("MenuEntryMsg is not yet implemented")

