#!/usr/bin/env python
import rospy
import ros_helper.msgs.sensor as sens
from ros_helper.simple_pub_sub import SimpleSyncSubscriber

def callback(msgs):
    pub.publish(sens.MultiJoyMsg(rospy.Time.now(), msgs))

if __name__=='__main__':
    rospy.init_node('multijoy_node')
    pub = rospy.Publisher('multijoy', sens.MultiJoyMsg, queue_size=1)
    SimpleSyncSubscriber(rospy, rospy.get_param('~joytopics'), sens.MultiJoyMsg, callback_handle=callback)
    rospy.spin()
